version: '3.7'
services:
  django:
    restart: always
    build: gyoseki-archive
    expose:
      - "3031"
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --env DJANGO_SETTINGS_MODULE=gyoseki_beta.settings_production gyoseki_beta.wsgi -b 0.0.0.0:3031 --access-logfile - --capture-output --log-level debug --limit-request-line 0"
    volumes:
      - $PWD/gyoseki-archive:/opt/apps
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - $PWD/gyoseki-archive/static:/opt/apps/static
      - $PWD/gyoseki-archive/media:/opt/apps/media